require File.expand_path('nbt/tag/exceptions', File.dirname(__FILE__))

require File.expand_path('nbt/tag', File.dirname(__FILE__))
require File.expand_path('nbt/tag/end', File.dirname(__FILE__))
require File.expand_path('nbt/tag/byte', File.dirname(__FILE__))
require File.expand_path('nbt/tag/short', File.dirname(__FILE__))
require File.expand_path('nbt/tag/int', File.dirname(__FILE__))
require File.expand_path('nbt/tag/long', File.dirname(__FILE__))
require File.expand_path('nbt/tag/float', File.dirname(__FILE__))
require File.expand_path('nbt/tag/double', File.dirname(__FILE__))
require File.expand_path('nbt/tag/byte_array', File.dirname(__FILE__))
require File.expand_path('nbt/tag/string', File.dirname(__FILE__))
require File.expand_path('nbt/tag/list', File.dirname(__FILE__))
require File.expand_path('nbt/tag/compound', File.dirname(__FILE__))
